#!/bin/sh

# $1 = SUBNET
_route_added_by_script() {
    local COUNT=$( ip route | grep "^$1" | grep -c "dev $INTERFACE" )
    [ ${COUNT:-0} -gt 0 ]
}

if _route_added_by_script $SUBNET ; then
    echo "INFO: delete route to $SUBNET"
    ip route del $SUBNET dev $INTERFACE
else
    echo "INFO: skip host-configured route to $SUBNET"
fi
