#!/bin/sh

HOST_CONF=$( dirname $0 )/hosts/$NAME

# $1 = SUBNET
_route_exist() {
    local COUNT=$( ip route get $1 | grep -c "dev \\(${INTERFACE}\\|lo\\)" )
    [ ${COUNT:-0} -gt 0 ]
}

# $1 = ADDR
_is_host() {
    local IS_HOST=$( cat $HOST_CONF | grep -i "Subnet\\s*=\\s*" | grep -c "$1" )
    [ ${IS_HOST:-0} -gt 0 ]
}

if _is_host $SUBNET ; then
    echo "INFO: skip host route: $SUBNET"
else
    if _route_exist $SUBNET ; then
        echo "INFO: skip existing route: $SUBNET"
    else
        echo "INFO: add route: $SUBNET"
        ip route add $SUBNET dev $INTERFACE
    fi
fi

