#!/bin/sh

# $1 = SUBNET
_route_exist() {
    local COUNT=$( ip route | grep -c "^$1" )
    [ ${COUNT:-0} -gt 0 ]
}

# $1 = ADDR
_is_host() {
    local IS_SRC=$( ip route | grep -c "src $1" )
    [ $IS_SRC ]
}

if _route_exist $SUBNET ; then
    if _is_host ; then
        echo "INFO: skip host route: $SUBNET"
    else
        echo "INFO: skip existing route to $SUBNET"
    fi
else
    echo "INFO: add route for $SUBNET"
    ip route add $SUBNET dev $INTERFACE
fi;
