#!/bin/sh

DIR=$( dirname $0 )
HOST_CONF=${DIR}/hosts/${NAME}
RC=${DIR}/tinc-up.rc

TINC_IP=$( cat $HOST_CONF | grep -i 'SelfIP' | awk -F '\\s*=\\s*' '{print $2}' )

if [ ! $TINC_IP ]; then
    echo "ERROR: Tinc IP of $NAME is not set, add 'SelfIP = <ip>' in host config!"
    echo "ERROR: Interface startup aborted."
    exit 2
fi

ifconfig $INTERFACE $TINC_IP netmask 255.255.0.0 \
&& echo "INFO: link $INTERFACE up, addr $TINC_IP" \
|| exit 1

if [[ -e $RC ]]; then
    source $RC
fi
